SELECT NAME, COUNT(P.ID) AS PROJECT_COUNT,  FROM CLIENT C
JOIN PROJECT P ON C.ID = P.CLIENT_ID
WHERE C.ID IN (
   SELECT CLIENT_ID FROM PROJECT
   GROUP BY CLIENT_ID
   HAVING COUNT(P.ID) IN (
     SELECT COUNT(P.ID) 
     FROM PROJECT GROUP BY CLIENT_ID 
     ORDER BY COUNT(P.ID) DESC
     LIMIT 1
   )
) GROUP BY C.ID