SELECT CONCAT('PROJECT ', ID) AS NAME, DATEDIFF(MONTH, START_DATE, FINISH_DATE) MONTH_COUNT FROM PROJECT
WHERE DATEDIFF(MONTH, START_DATE , FINISH_DATE ) IN (
    SELECT MAX (DATEDIFF(MONTH, START_DATE , FINISH_DATE )) FROM PROJECT
)