
SELECT 'YOUNGEST' TYPE, NAME, BIRTHDAY FROM worker
GROUP BY NAME
HAVING BIRTHDAY IN(
    SELECT MAX (BIRTHDAY) FROM WORKER
)
UNION
SELECT 'OLDEST' TYPE, NAME, BIRTHDAY FROM worker
GROUP BY NAME
HAVING BIRTHDAY IN (
    SELECT MIN (BIRTHDAY) FROM WORKER
) ORDER BY TYPE DESC