CREATE TABLE WORKER (
   ID INT PRIMARY KEY,
   NAME VARCHAR (1000) NOT NULL,
   BIRTHDAY DATE CHECK (DATA > '1900-01-01'),
   LEVEL VARCHAR CHECK (LEVEL IN('Trainee', 'Junior', 'Middle', 'Senior')) NOT NULL,
   SALARY INT CHECK (SALARY > 100 AND SALARY < 100001)
)

CREATE TABLE client (
   ID INT PRIMARY KEY,
   NAME VARCHAR (1000) NOT NULL
)

CREATE TABLE PROJECT (
   ID INT PRIMARY KEY,
   CLIENT_ID INT NOT NULL,
   START_DATE DATE NOT NULL,
   FINISH_DATE DATE
)

ALTER TABLE PROJECT ADD CONSTRAINT CLIENT_ID_FK FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT (ID)

CREATE TABLE PROJECT_WORKER (
  PROJECT_ID INT NOT NULL,
  WORKER_ID INT NOT NULL,
  PRIMARY KEY (PROJECT_ID, WORKER_ID),
  FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT (ID),
  FOREIGN KEY (WORKER_ID) REFERENCES WORKER (ID)
)