SELECT CONCAT ('Project ', PROJECT_ID) AS NAME, SUM (SALARY)*DATEDIFF(MONTH, START_DATE , FINISH_DATE) AS PRICE
FROM WORKER W, PROJECT_WORKER PW, PROJECT P
WHERE PW.WORKER_ID =W.ID AND PW.PROJECT_ID = P.ID
GROUP BY PROJECT_ID
ORDER BY PRICE DESC